export const CHECK_MASTER_CODE = 'CHECK_MASTER_CODE'
export const SUBMIT_PASSCODE = 'SUBMIT_PASSCODE'
export const SERVICE_MODE = 'SERVICE_MODE'
export const MASTER_CODE_CONFIRMED = 'MASTER_CODE_CONFIRMED'